# Generated by Django 5.2.7 on 2025-10-28 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_congreso_allowedemaildomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre del nivel')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('congreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_levels', to='base.congreso')),
            ],
            options={
                'ordering': ['congreso__name', 'order', 'name'],
                'unique_together': {('congreso', 'name')},
            },
        ),
    ]
