# Generated by Django 5.2.7 on 2025-10-28 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_performancelevel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performancelevel',
            options={'ordering': ['congreso__name', 'name']},
        ),
        migrations.RemoveField(
            model_name='performancelevel',
            name='order',
        ),
    ]
