# Generated by Django 5.2.7 on 2025-10-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_performancelevel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='congreso',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
