# Generated by Django 5.2.7 on 2025-11-02 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_usercongresomembership'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usercongresomembership',
            new_name='base_userco_congres_db9174_idx',
            old_name='base_userco_congres_efca7e_idx',
        ),
    ]
