# Generated by Django 5.2.7 on 2025-11-02 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_base_userco_congres_efca7e_idx_base_userco_congres_db9174_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='congreso',
            name='access_password_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='usercongresomembership',
            name='performance_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='base.performancelevel'),
        ),
    ]
