# Generated by Django 5.2.7 on 2025-11-02 21:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_congreso_access_password_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usercongresomembership',
            name='email_normalized',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AddConstraint(
            model_name='usercongresomembership',
            constraint=models.UniqueConstraint(fields=('congreso', 'email_normalized'), name='uniq_membership_congreso_emailnorm'),
        ),
    ]
