# Generated by Django 5.2.7 on 2025-11-03 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_usercongresomembership_email_normalized_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nombre de la conferencia')),
                ('image', models.ImageField(blank=True, null=True, upload_to='conferencias/')),
                ('lugar', models.CharField(blank=True, max_length=200, verbose_name='Lugar')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('congreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferencias', to='base.congreso')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conferencias_imparte', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['congreso__name', 'title'],
                'unique_together': {('congreso', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nombre del taller')),
                ('image', models.ImageField(blank=True, null=True, upload_to='talleres/')),
                ('lugar', models.CharField(blank=True, max_length=200, verbose_name='Lugar')),
                ('cupo_maximo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cupo máximo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('congreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talleres', to='base.congreso')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talleres_imparte', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['congreso__name', 'title'],
                'unique_together': {('congreso', 'title')},
            },
        ),
    ]
