# Generated by Django 5.2.7 on 2025-11-03 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_conferencia_taller'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('individual', 'Individual'), ('grupal', 'Grupal')], default='individual', max_length=12)),
                ('title', models.CharField(max_length=200, verbose_name='Nombre del concurso')),
                ('image', models.ImageField(blank=True, null=True, upload_to='concursos/')),
                ('lugar', models.CharField(blank=True, max_length=200, verbose_name='Lugar')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('cupo_maximo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cupo máximo')),
                ('numero_equipos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de equipos')),
                ('max_por_equipo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número máximo por equipo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('congreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concursos', to='base.congreso')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concursos_imparte', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['congreso__name', 'title'],
                'unique_together': {('congreso', 'title')},
            },
        ),
    ]
