# Generated by Django 5.2.7 on 2025-11-07 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_congreso_admin_scope'),
        ('base', '0017_extrafield_rolesection'),
    ]

    operations = [
    ]
