# Generated by Django 5.2.7 on 2025-11-09 01:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_merge_20251107_0010'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='congresoadminscope',
            name='uniq_scope_user_congreso',
        ),
        migrations.RenameIndex(
            model_name='concursoinscripcion',
            new_name='base_concur_congres_856b54_idx',
            old_name='base_cons_insc_idx',
        ),
        migrations.RenameIndex(
            model_name='conferenciainscripcion',
            new_name='base_confer_congres_7c6e0d_idx',
            old_name='base_conf_insc_idx',
        ),
        migrations.RenameIndex(
            model_name='tallerinscripcion',
            new_name='base_taller_congres_321127_idx',
            old_name='base_taller_insc_idx',
        ),
        migrations.AddField(
            model_name='conferencia',
            name='cupo_maximo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cupo máximo'),
        ),
        migrations.AlterField(
            model_name='concursoinscripcion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='conferenciainscripcion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tallerinscripcion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='congresoadminscope',
            unique_together={('user', 'congreso')},
        ),
    ]
