# Generated by Django 5.2.7 on 2025-11-14 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_set_utf8mb4_unicode_ci'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcursoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='base.concurso')),
                ('congreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_concurso', to='base.congreso')),
                ('lider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_liderados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['concurso__title', 'nombre'],
                'unique_together': {('concurso', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='ConcursoEquipoMiembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='base.concursoequipo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_concurso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['equipo__nombre', 'user__username'],
                'unique_together': {('equipo', 'user')},
            },
        ),
    ]
