# Generated by Django 5.2.7 on 2025-11-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_extrafield_unique_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concurso',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Nombre del concurso'),
        ),
        migrations.AlterField(
            model_name='conferencia',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Nombre de la conferencia'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Nombre del taller'),
        ),
    ]
