# Generated by Django 5.2.7 on 2025-12-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_userextrafieldvalue_uniq_extrafieldvalue_field_congreso_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextrafieldvalue',
            name='value',
            field=models.CharField(max_length=500, verbose_name='Valor'),
        ),
    ]
